### ISSUE TITLE
Task review

### ISSUE THREAD

**Issue by IamLizu** [rifadul/React-Weather-app-with-Typescript#1]
1. Button should be disabled if the input field is empty
https://github.com/rifadul/React-Weather-app-with-Typescript/blob/583da179e2fad489c83cf187b1151cf390971820/src/components/Home.tsx#L30

2. No flag is appearing in the country details page
https://github.com/rifadul/React-Weather-app-with-Typescript/blob/583da179e2fad489c83cf187b1151cf390971820/src/components/CountryDetails.tsx#L74

**Comment by rifadul** [comment]
> 1. Button should be disabled if the input field is empty
>    https://github.com/rifadul/React-Weather-app-with-Typescript/blob/583da179e2fad489c83cf187b1151cf390971820/src/components/Home.tsx#L30
> 2. No flag is appearing in the country details page
>    https://github.com/rifadul/React-Weather-app-with-Typescript/blob/583da179e2fad489c83cf187b1151cf390971820/src/components/CountryDetails.tsx#L74

Issue solved. Thanks for the review.
